### PR TITLE
remove obsolete add-module option from luke start scripts

### PR DESCRIPTION
**Pull request by mocobeta**
https://github.com/apache/lucene/pull/533#issuecomment-996742260

(This also includes the cherry-picked javadoc.)

### CODE REVIEW

**Comment by mocobeta** [comment]
This was already committed so i'm closing this.
https://github.com/apache/lucene/pull/533/commits/8610176a42d613ea8633ef3e9bd458e1a2baba3d

**Comment by uschindler** [comment]
I did not apply your javadocs fix, sorry. Can you reopen so I can merge?

**Comment by mocobeta** [comment]
The javadocs fix has been commited to main, so merging main branch would fix it. (Though I am not sure the proper workflow to do so...)
https://github.com/apache/lucene/commit/c64e5fe84c4990968844193e3a62f4ebbba638ea

**Comment by uschindler** [comment]
Merged it from main. It's plain easy: Go to your dweiss/jms2 checkout and pull changes from origin/main.

**Comment by mocobeta** [comment]
ah yes, i know the git commands. i just hesitated to push to the jms branch.

**Comment by uschindler** [comment]
@mocobeta I was always wondering why you not do this. There is no need to create pull requests for pull requests. The ASF github settings automatically give all committers rights to push to all branches of pull request. Dawid and I are happy if you commit to the PR branch. No need for reluctance!

**Pull request closed without merging**
